name: deploy github pages

on:
  push:
    branches:
      - master  # Set a branch name to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-verison: '12.x'

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: install dependency
        run: npm ci

      - name: build project
        run: npm run build:ci -- --progress

      - name: copy files to public
        run: |
          mkdir ./public
          mkdir ./public/node_modules
          cp -r ./dist ./public/dist
          cp -r ./scenes ./public/scenes
          cp -r ./node_modules/cannon ./public/node_modules/cannon
          cp index.html ./public/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public